swagger: '2.0'
info:
  version: 0.0.1
  title: Zhidan
  description: 知单(Zhidan)智慧餐厅系统后端API文档
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /restaurant/account:
    get:
      summary: Verify manager's number.
      parameters: 
        - in: query
          name: number
          type: string
          description: manager's number
      responses:
        200:
          description: OK
    post:
      summary: Sign up restaurant account
      consumes:
        - application/x-www-form-urlencoded
      parameters: 
        - in: formData
          name: number
          type: string
          description: manager's number
        - in: formData
          name: password
          type: string
          description: manager's password
        - in: formData
          name: restaurant_name
          type: string
          description: restaurant name
      responses:
        201:
          description: OK
  /restaurant/session:
    post:
      summary: Sign in restaurant account at first and create session
      consumes:
        - application/x-www-form-urlencoded
      parameters: 
        - in: formData
          name: number
          type: string
          description: manager's number
        - in: formData
          name: password
          type: string
          description: manager's password
      responses:
        201:
          description: OK
    
        